# Set the project language
language: python

# Set up the build matrix
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

# Install testing dependencies (nose is pre-installed) and the module itself
# in order to get dependencies
install:
  - sudo apt-get -qq update
  - pip install pep8
  - if [ "$TRAVIS_PYTHON_VERSION" == '2.7' ]; then pip install ipython pyzmq; fi
  - pip install git+https://github.com/havoc-io/owls-cache.git
  - pip install -e .

# Start an IPython cluster
before_script:
 - if [ "$TRAVIS_PYTHON_VERSION" == '2.7' ]; then ipcluster start -n 2 & sleep 60; fi

# Run PEP-8 compliance testing and unit tests
script:
  - common/scripts/run-pep8.sh
  - common/scripts/run-tests.sh

# Send notifications
notifications:
  email:
    - jacob@havoc.io
